# Kubernetes service for grafana
apiVersion: v1
kind: Service
metadata:
  labels: null
  name: influxdb-grafana-svc
spec:
  type: LoadBalancer
#  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000 
  selector:
    app: influxGrafana
